name: CI Pipeline

on:
  push:
    branches: [dev, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Vérification des fichiers
        run: |
          echo "Liste des fichiers"
          ls -la

      - name: Test simple HTML
        run: |
          test -f index.html
          test -f style.css
          echo "Tests OK"

      - name: Génération de l'artefact
        run: |
          mkdir build
          cp index.html style.css build/

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: build/
